### ISSUE TITLE
Type tokensManager not exported

### ISSUE THREAD

**Issue by ChristianLohmann** [zalando/go-tokens#14]
I don't know if it is intended that `type tokensManager struct` is not exported. But if it is the case, how can i use the "managed" `tokensManager` outside the scope of the invoked function?

**Comment by lmineiro** [comment]
This was, indeed, intended.

None of its members are exported and the API is only about the Manage() and Get() methods.

Example:
  https://github.com/zalando/clair-sqs/blob/master/cmd/receiver/main.go#L63
  https://github.com/zalando/clair-sqs/blob/master/cmd/receiver/main.go#L82

**Comment by ChristianLohmann** [comment]
The examples above show the usage of the `tokensManager` only in the main function. My use case was to have some `init()` of the tokensManager and use it then as some kind of singleton in other functions. I just wanted to encapsulate the tokens logic somehow.

**Comment by lmineiro** [comment]
I see the pain. Declaring such singleton variable as interface{} would be a PITA. We'll change this. Thanks for the suggestion.

**Comment by ChristianLohmann** [comment]
Thanks for that!
